import { Router, Request, Response } from 'express';
import PDFDocument from 'pdfkit';

export const exportRoute = Router();

exportRoute.post('/pdf', (req: Request, res: Response) => {
  try {
    const { content, title = 'Intuita Export', metadata } = req.body;
    if (!content) return res.status(400).json({ error: 'content is required' });

    const doc = new PDFDocument({ margin: 72, size: 'A4' });
    const filename = `intuita-${title.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    // Header
    doc.fontSize(22).font('Helvetica-Bold').text('INTUITA', { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(11).font('Helvetica').fillColor('#888888')
       .text(`Zero-Prompt AI Engine  ·  Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'left' });

    // Divider
    doc.moveDown(0.8);
    doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).stroke('#DDDDDD');
    doc.moveDown(0.8);

    // Metadata badges
    if (metadata) {
      doc.fontSize(9).fillColor('#888888').font('Helvetica');
      const parts = [
        metadata.goalType   && `Type: ${metadata.goalType}`,
        metadata.toneLabel  && `Tone: ${metadata.toneLabel}`,
        metadata.purpose    && `Purpose: ${metadata.purpose}`,
        metadata.wordCount  && `Words: ${metadata.wordCount}`,
      ].filter(Boolean);
      doc.text(parts.join('   ·   '), { align: 'left' });
      doc.moveDown(1);
    }

    // Title
    if (title && title !== 'Intuita Export') {
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#111111').text(title);
      doc.moveDown(0.8);
    }

    // Body content
    doc.fontSize(11).font('Helvetica').fillColor('#222222');
    const lines = content.split('\n');
    lines.forEach((line: string) => {
      const trimmed = line.trim();
      if (trimmed.startsWith('## ')) {
        doc.moveDown(0.5);
        doc.fontSize(13).font('Helvetica-Bold').fillColor('#111111').text(trimmed.replace('## ', ''));
        doc.fontSize(11).font('Helvetica').fillColor('#222222');
        doc.moveDown(0.3);
      } else if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
        doc.font('Helvetica-Bold').text(trimmed.replace(/\*\*/g, ''));
        doc.font('Helvetica');
      } else if (trimmed.startsWith('• ') || trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        doc.text(`  ${trimmed}`, { indent: 10 });
      } else if (trimmed.match(/^\d+\./)) {
        doc.text(`  ${trimmed}`, { indent: 10 });
      } else if (trimmed === '') {
        doc.moveDown(0.4);
      } else {
        doc.text(trimmed, { lineGap: 3 });
      }
    });

    // Footer
    doc.moveDown(2);
    doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).stroke('#DDDDDD');
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor('#AAAAAA')
       .text('Generated by Intuita · intuita.ai · Zero-Prompt AI Engine', { align: 'center' });

    doc.end();
  } catch (err: any) {
    console.error('Export error:', err.message);
    return res.status(500).json({ error: err.message || 'PDF export failed' });
  }
});
